# Catalogue Experiment: Baroque AI

```
Nextcloud Markdown document link: https://tib.eu/cloud/s/qBx8SbqiPBBedye 
```

## Part of the series: Baroque TOC

* Class instructions and all links: <https://nfdi4culture.github.io/class-ADA-CP-pipeline/>
* Demo publication: <https://nfdi4culture.github.io/catalogue-003/>
* Repo link: <https://github.com/NFDI4Culture/catalogue-003>

---

## Add your name:

* Josef Debase

## Text editing

Die Botanik ist ein Segment der Biologie, die sich mit der intensiven Wissenschaft der Pflanzen befasst. Dieser Bereich der Biologie ist ein Teil der Naturwissenschaft, die sich intensiv mit allem Leben und allen Lebewesen unserer Erde beschäftigt. Die Pflanzenkunde oder Pflanzenbiologie (Lehre der Botanik) befasst sich in ihrem Inhalt mit allem was die Welt der Pflanzen betrifft. Dazu gehören Wachstum, Fortpflanzung oder Aufbau sowie Inhaltsstoffe, mögliche Krankheiten oder der wirtschaftliche Nutzeffekt für den Menschen. Unter der Berücksichtung dieser Kriterien entsteht eine Einteilung der Pflanzen in Heilmittel, Nahrungsmittel und Rohstoffe.
Anhand dieser Definition erklärt sich das Berufsfeld des Botanikers. In der Folge ergibt sich, dass die Botanik die Wissenschaft ist und der Botaniker ein Wissenschaftler, der sich diesem überaus interessanten Teilstück der Biologie verschrieben hat.
<https://openai.com/blog/chatgpt>

<https://www.perplexity.ai/>

