project:
  type: website

website:
  title: "Quarto Create-project /Users/josefdebase/Documents/github/my-collection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



